replicaCount: 2

image:
  repository: vikusido/app-fixed
  pullPolicy: IfNotPresent
  tag: latest

podAnnotations: {}

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30090

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

nodeSelector: {}

tolerations: []

affinity: {}

appPath: /demo/
